-- USER SQL
CREATE USER "DUKE" IDENTIFIED BY "Machinee1Car001."  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "DUKE" QUOTA UNLIMITED ON "DATA";

-- ROLES
GRANT "CONNECT" TO "DUKE" ;
GRANT "RESOURCE" TO "DUKE" ;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY SEQUENCE TO "DUKE" ;
GRANT CREATE ANY TABLE TO "DUKE" ;
--------------------------------------------------------
--  DDL for Table EXPERIMENTS
--------------------------------------------------------

  CREATE TABLE "DUKE"."EXPERIMENTS" 
   (	"ID" NUMBER(3,0), 
	"TASK" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"COMPLETE" NUMBER(1,0), 
	"OWNER" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'DUKE'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index EXPERIMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DUKE"."EXPERIMENTS_PK" ON "DUKE"."EXPERIMENTS" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table EXPERIMENTS
--------------------------------------------------------

  ALTER TABLE "DUKE"."EXPERIMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."EXPERIMENTS" MODIFY ("TASK" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."EXPERIMENTS" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."EXPERIMENTS" ADD CONSTRAINT "EXPERIMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;


--------------------------------------------------------
--  DDL for Table MEASUREMENTS
--------------------------------------------------------

  CREATE TABLE "DUKE"."MEASUREMENTS" 
   (	"ID" NUMBER(3,0), 
	"VALUE" NUMBER(10,3), 
	"UNIT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"TIME" NUMBER(5,0), 
	"EXP_ID" NUMBER(3,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index MEASUREMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DUKE"."MEASUREMENTS_PK" ON "DUKE"."MEASUREMENTS" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MEASUREMENTS
--------------------------------------------------------

  ALTER TABLE "DUKE"."MEASUREMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."MEASUREMENTS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."MEASUREMENTS" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."MEASUREMENTS" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."MEASUREMENTS" MODIFY ("EXP_ID" NOT NULL ENABLE);
  ALTER TABLE "DUKE"."MEASUREMENTS" ADD CONSTRAINT "MEASUREMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEASUREMENTS
--------------------------------------------------------

  ALTER TABLE "DUKE"."MEASUREMENTS" ADD CONSTRAINT "MEA_EXP_FK" FOREIGN KEY ("EXP_ID")
	  REFERENCES "DUKE"."EXPERIMENTS" ("ID") ENABLE;

create sequence EXP_SEQ  start with 102 increment by 1 nocycle;

create sequence MEA_SEQ start with 9 increment by 1 nocycle;


INSERT INTO "DUKE"."EXPERIMENTS" (ID, TASK, COMPLETE, OWNER) VALUES ('100', 'Measure Temperarture Change', '1', 'DUKE');

INSERT INTO "DUKE"."EXPERIMENTS" (ID, TASK, COMPLETE, OWNER) VALUES ('101', 'Changes in global average surface temperature', '0', 'DUKE');


INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('1', '291.25', 'K', '0', '100');

INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('2', '289.55', 'K', '300', '100');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('3', '285.55', 'K', '600', '100');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('4', '0.99', 'C', '600', '101');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('5', '0.85', 'C', '1200', '101');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('6', '0.93', 'C', '1500', '101');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('7', '1.02', 'C', '1700', '101');
INSERT INTO "DUKE"."MEASUREMENTS" (ID, VALUE, UNIT, TIME, EXP_ID) VALUES ('8', '0.90', 'C', '2000', '101');

commit;


