apiVersion: v1
kind: Service
metadata:
  labels:
    app: dukelabs
  name: dukelabs
spec:
  selector:
    app: dukelabs
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dukelabs
  name: dukelabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dukelabs
  template:
    metadata:
      labels:
        app: dukelabs
    spec:
      containers:
      - image: oustudent1/dukelabs:atp
        imagePullPolicy: IfNotPresent
        name: dukelabs
        volumeMounts:
        - mountPath: /home/oracle/labs/dukelabs_wallet
          name: wallet-config
        ports:
        - containerPort: 8080
      volumes:
      - name: wallet-config
        configMap:
           name: wallet

